# Change these first
owner: DIYgodLab # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Public - xLog
    url: 'https://xlog.app'

  - name: Public - RSSHub
    url: 'https://rsshub.app'

  - name: Public - RSSHub Docs
    url: 'https://docs.rsshub.app'

  - name: Public - DPlayer Docs
    url: 'https://dplayer.diygod.dev'

  - name: Public - APlayer Docs
    url: 'https://aplayer.js.org'

  - name: Personal - Blog
    url: 'https://diygod.cc'

  - name: Personal - Archived Blog
    url: 'https://archive.diygod.me'

  - name: Personal - Docker
    url: $URL_PERSONALDOCKER

  - name: Personal - Fog Machine
    url: $URL_PERSONALFOGMACHINE

  - name: Personal - Miniflux
    url: $URL_PERSONALMINIFLUX

  - name: Personal - n8n
    url: $URL_PERSONALN8N
    expectedStatusCodes:
      - 200
      - 401

  - name: Personal - NAS
    url: $URL_PERSONALNAS

  - name: Personal - NAS Status
    url: 'https://nas-status.diygod.me'

  - name: Personal - RSSHub
    url: $URL_PERSONALRSSHUB

  - name: Personal - Umami
    url: $URL_PERSONALUMAMI

  - name: Personal - Suannai
    url: 'https://suannai.cat'

  - name: Personal - Pal
    url: 'https://pal.diygod.me'

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.diygod.me
  baseUrl: /
  logoUrl: https://ipfs.crossbell.io/ipfs/bafybeibefx2tyow77m2wcnsh5anaaxfy7ypxbcuapb52c4h255onqp72ye
  name: DIYgod Status Page
  navbar:
    - title: Status
      href: /
    - title: Blog
      href: https://diygod.cc

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
